kakaomap-with-django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("map.urls")),
]

kakaomap-with-django/map/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("", views.search_map, name="search"),
    path("favorites/", views.favorites, name="favorites"),
    path("api/map/1", views.add_favorite, name="add_favorite"),
    path("api/map/2", views.update_favorite, name="update_favorite"),
    path("api/map/3", views.get_favorite, name="get_favorite"),
]

kakaomap-with-django/map/models.py
from django.db import models

# Create your models here.


class Favorite(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    jibun = models.CharField(max_length=100, blank=True, null=True)
    link = models.CharField(max_length=100, blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    lng = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.title

kakaomap-with-django/map/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Favorite


# Create your views here.


def search_map(request):
    return render(request, "map/search_map.html")


def favorites(request):
    return render(request, "map/favorites.html")


def add_favorite(request):
    title = request.POST.get("title")
    address = request.POST.get("address")
    jibun = request.POST.get("jibun")
    link = request.POST.get("link")
    lat = request.POST.get("lat")
    lng = request.POST.get("lng")

    try:
        my_fav = Favorite.objects.get(title=title)
        my_fav.delete()
        result = {"text": "☆", "color": "black"}
    except Favorite.DoesNotExist:
        fav = Favorite.objects.create(
            title=title, address=address, jibun=jibun, link=link, lat=lat, lng=lng
        )
        result = {"text": "★", "color": "yellow"}

    return HttpResponse(json.dumps(result), content_type="application/json")


def update_favorite(request):
    title = request.POST.get("title")

    try:
        my_fav = Favorite.objects.get(title=title)
        result = {"text": "★", "color": "yellow"}
    except Favorite.DoesNotExist:
        result = {"text": "☆", "color": "black"}

    return HttpResponse(json.dumps(result), content_type="application/json")


def get_favorite(request):
    favs = serializers.serialize("json", Favorite.objects.all())
    return HttpResponse(favs, content_type="application/json")

kakaomap-with-django/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}{% endblock meta %}

    <!-- title -->
    <title>{% block title %}{% endblock title %}</title>

    <!-- link -->
    <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    {% block link %}{% endblock link %}

    <!-- head Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=1087e575a59f0ecd45887863b56a20f1&libraries=services,clusterer"></script>
    {% block head_script %}{% endblock head_script %}
</head>

<body>
    {% include "partials/navigation.html" %}

    <!-- main content -->
    <div id="root">
        {% block content %}{% endblock content %}
    </div>

    <!-- Script -->
    {% block script %}{% endblock script %}
</body>

</html>

kakaomap-with-django/templates/map/favorites.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}{% endblock meta %}

{% block title %}Favorites{% endblock title %}

{% block link %}
<link rel="stylesheet" href="{% static 'map/css/search_map.css' %}">
<link rel="stylesheet" href="{% static 'map/css/favorites.css' %}">
{% endblock link %}

{% block head_script %}
{% endblock head_script %}






{% block content %}
<div class="map"></div>
<div class="search-wrapper">
    <ul class="search-results">
    </ul>
</div>
{% endblock content %}

{% block script %}
<script>
    const favs = "{{favs}}"
    const api_url = "{% url 'map:add_favorite' %}"
    const update_api_url = "{% url 'map:update_favorite' %}"
    const get_api_url = "{% url 'map:get_favorite' %}"
    const csrf = "{{csrf_token}}"
</script>
<script src="{% static 'map/js/favorites.js' %}"></script>
{% endblock script %}

kakaomap-with-django/templates/map/my_map.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}{% endblock meta %}

{% block title %}Favorites{% endblock title %}

{% block link %}
<link rel="stylesheet" href="{% static 'map/css/my_map.css' %}">
{% endblock link %}

{% block head_script %}{% endblock head_script %}






{% block content %}



{% block script %}{% endblock script %}
{% endblock content %}

kakaomap-with-django/templates/map/search_map.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}{% endblock meta %}

{% block title %}Search Map{% endblock title %}

{% block link %}
<link rel="stylesheet" href="{% static 'map/css/search_map.css' %}">
{% endblock link %}

{% block head_script %}
{% endblock head_script %}






{% block content %}
<div class="map"></div>
<div class="search-wrapper">
    <form class="search-form" onsubmit="searchPlaces(); return false;">
        <input type="search" name="" class="search-form__keyword">
        <input type="submit" value="검색" class="search-form__button">
    </form>
    <ul class="search-results">
    </ul>
</div>
{% endblock content %}

{% block script %}
<script>
    const csrf = "{{csrf_token}}"
    const api_url = "{% url 'map:add_favorite' %}"
    const update_api_url = "{% url 'map:update_favorite' %}"
</script>
<script src="{% static 'map/js/searchMap.js' %}"></script>
{% endblock script %}

kakaomap-with-django/templates/partials/navigation.html
<nav>
    <a class="nav__item" href="{% url 'map:search' %}">Home</a>
    <a class="nav__item" href="{% url 'map:favorites' %}">Favorites</a>
</nav>